trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '*/.sln'  # Chemin vers la solution ou le fichier de build

stages:
- stage: Build
  displayName: 'Build Front-end and Back-end'
  jobs:
  - job: BuildFrontEnd
    displayName: 'Build Front-end'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build Front-end'

    # Publish front-end artifacts
    - publish: $(System.DefaultWorkingDirectory)/frontend/dist
      artifact: frontend-dist

  - job: BuildBackEnd
    displayName: 'Build Back-end'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        cd backend
        npm install
        npm run build
      displayName: 'Build Back-end'

    # Publish back-end artifacts
    - publish: $(System.DefaultWorkingDirectory)/backend/dist
      artifact: backend-dist

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download Build Artifacts'

